npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "25AA7E89-93A8-4C8D-A7F9-D132BA7509C1"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "25AA7E89-93A8-4C8D-A7F9-D132BA7509C1"